// <auto-generated />
using System;
using CommandStore.FluxoCaixa;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Store.Migrations
{
    [DbContext(typeof(FluxoCaixaContext))]
    [Migration("20251113215601_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FluxoCaixa.LancamentoRegistrar.Entity.ConsolidadoDiario", b =>
                {
                    b.Property<DateTime>("DataConsolidacao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalCreditos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebitos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DataConsolidacao");

                    b.ToTable("ConsolidadosDiarios");
                });

            modelBuilder.Entity("FluxoCaixa.LancamentoRegistrar.Entity.Lancamento", b =>
                {
                    b.Property<int>("IdLancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLancamento"));

                    b.Property<DateTime>("DataConsolidacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdLancamento");

                    b.HasIndex("DataConsolidacao");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("FluxoCaixa.LancamentoRegistrar.Entity.Lancamento", b =>
                {
                    b.HasOne("FluxoCaixa.LancamentoRegistrar.Entity.ConsolidadoDiario", null)
                        .WithMany("Lancamentos")
                        .HasForeignKey("DataConsolidacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FluxoCaixa.LancamentoRegistrar.Entity.ConsolidadoDiario", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
